# Generated by Django 6.0.6 on 2026-06-08 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Número')),
                ('is_covered', models.BooleanField(default=False, verbose_name='Coberta')),
                ('status', models.CharField(choices=[('Livre', 'Livre'), ('Ocupada', 'Ocupada'), ('Reservada', 'Reservada')], default='Livre', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Término')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mensalidade')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='customers.customer', verbose_name='Cliente')),
                ('parking_spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='parking.parkingspot', verbose_name='Vaga')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['id'],
            },
        ),
    ]
