# Generated by Django 6.0.6 on 2026-06-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='occupied_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ocupada desde'),
        ),
    ]
