# Generated by Django 6.0.6 on 2026-06-08 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('issue_date', models.DateField(verbose_name='Data de Emissão')),
                ('service_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='operations.serviceorder', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['id'],
            },
        ),
    ]
