# Generated by Django 6.0.6 on 2026-06-08 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('base_price', models.FloatField(verbose_name='Preço Base')),
            ],
            options={
                'verbose_name': 'Categoria de Serviço',
                'verbose_name_plural': 'Categorias de Serviço',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(verbose_name='Entrada')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Saída')),
                ('status', models.CharField(choices=[('Aberta', 'Aberta'), ('Finalizada', 'Finalizada')], default='Aberta', max_length=20, verbose_name='Status')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Cliente')),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingspot', verbose_name='Vaga')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('unit_price', models.FloatField(verbose_name='Preço Unitário')),
                ('subtotal', models.FloatField(verbose_name='Subtotal')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.servicecategory', verbose_name='Categoria')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.serviceorder', verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Item de Serviço',
                'verbose_name_plural': 'Itens de Serviço',
                'ordering': ['id'],
            },
        ),
    ]
